server:
  port: 8080

spring:
  application:
    name: kafka-spring-demo
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_GROUP_ID:demo-spring-consumer}
      auto-offset-reset: earliest
